config/routes.rb
Rails.application.routes.draw do
  resources :documents
  resources :to_dos
  get 'tags/', to: 'dashboard#index'
  get 'tags/:tag', to: 'tag#index', as: :tag
  resources :notes
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'dashboard#index'
end

app/models/note.rb
require 'elasticsearch/model'

class Note < ApplicationRecord

  belongs_to :user
  has_many :to_dos, dependent: :destroy
  has_many :documents
  acts_as_taggable

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  def has_to_dos?
    if self.to_dos.length == 0
      return false
    else
      return true
    end
  end

  def has_documents?
    if self.documents.length == 0
      return false
    else
      return true
    end
  end
 

  def has_open_to_dos?
    open = false
    self.to_dos.each do |t|
      if t.not_achieved?
        open = true
      end
    end
    return open
  end

  def self.search(query)
    __elasticsearch__.search(
      {
        query: {
          multi_match: {
            query: query,
            fields: ['title^10', 'summary^5','text']
          }
        }
      }
    )
  end

end

Note.import force: true

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    if params[:q].nil? or params[:q]==""
      @notes = current_user.notes
    else
      @notes = current_user.notes.search(params[:q]).records
    end

    @tags = @notes.tag_counts.order(taggings_count: :desc).first(40).sort_by {|t| t.name}

    if params[:tag]
      @tag = params[:tag]
      @notes = @notes.tagged_with(params[:tag])
    end

    @notes = @notes.order(updated_at: :desc).page(params[:page]).per(5)

  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)
    @note.user = current_user

    respond_to do |format|
      if @note.save
        @note.__elasticsearch__.index_document
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = current_user.notes.find(params[:id]) # Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:title, :summary, :text, :user_id, :tag_list)
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<%= form_for(note) do |f| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :summary %>
    <%= f.text_area :summary, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :tag_list, "Tags (separated by commas)" %><br />
    <%= f.text_field :tag_list, value: note.tag_list.map {|t| t}.join(', '), class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :text %>
    <%= f.text_area :text, :class => "tinymce", :rows => 12 %>
    <%= tinymce :content_css => asset_path('application.css') %>
  </div>

  <div class="actions">
    <%= f.submit "Save & Quit", class: "btn btn-primary btn-sm"  %>
  </div>
<% end %>

app/views/notes/_note_summary.html.erb
<div class="row" style="margin-bottom: 40px;margin-top: 20px;">
    <div class="col-sm-8">
        
        <div class="container-fluid">
            <div class="row">
                <%= link_to note do %>
                    <div class="col-sm-12 note">
                        <h2><%= note.title %></h2>
                        <p class="note_summary"><%= note.summary %></p>
                    </div>
                <% end %>
             </div>
            <div class="row">
                <div class="col-sm-4">
                    <%= link_to 'Edit', edit_note_path(note),
                        class: "btn btn-warning btn-sm" %>
                    <%= link_to 'Delete', note, method: :delete,
                        class: "btn btn-danger btn-sm",
                        data: { confirm: 'Are you sure?' } %>
                </div>
                <div class="col-sm-4">
                    <p>Tags:
                        <%= sanitize note.tag_list.map { |t| link_to t, tag_path(t) }.join(', '), tags: %w(a), attributes: %w(href ) %>
                    </p>
                </div>
                <div class="col-sm-4 text-right">
                    <p class="note_infos text-right">
                        Created on <%= note.created_at.localtime.strftime("%a, %b %d, %Y at %H:%M") %><br>
                        Last updated on <%= note.updated_at.localtime.strftime("%a, %b %d, %Y at %H:%M") %><br>
                    </p>
                </div> 
            </div>
        </div>

    </div>
    <div class="col-sm-3">
        <% if note.has_documents? %>
            <h4 class="todos_title">Documents and files</h4>
            <% note.documents.each do |document| %>
                <p>
                <div class="media-left">
                  <%= if document.file?
                            link_to document.file_url do %>
                  <%= image_tag document.file_url(:small_thumb),
                                class: "media-object thumb" %>
                    <% end
                    end %>
                </div>
                <div class="media-body">
                  <h4 class="media-heading"><%= link_to document.title, document -%></h4>
                    <p class="document-list">
                        <%= link_to 'Download', document.file_url %>
                        (<%= number_to_human_size document.file.size -%>,
                         <%= document.file.file.extension.downcase-%>)
                    </p>
                </div>
                </p>

            <% end %>
        <% end %>
        <% if note.has_open_to_dos? %>
            <h4 class="todos_title">To Do's</h4>
            <%= render 'to_dos/todo_list', tasks: note.to_dos.order(:achieved, deadline: :asc) %>
        <% end %>
    </div>
</div>

app/views/notes/edit.html.erb
<% title @note.title %>

<h1></h1>
<%= render 'form', note: @note %>

<br>
<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<% title "Notes" %>

<div class="container-fluid">
	<div class="row">
		<div class="col-sm-6">
			<h1><%= yield :title %></h1>
		</div>
		<div class="col-sm-6 text-right" style="padding-top: 18px">

			<%= form_tag('/notes', method: :get, class: "form-inline") do  %>
				<div class="form-group">
			    <%= text_field_tag :q, params[:q], class: "form-control"  %>
				</div>
				<%= submit_tag "Search", class: "btn btn-primary btn-sm" %>
			<% end %>

			
		</div>
	</div>
	<div class="row">
		<div class="col-sm-6">
		<%= paginate @notes, :theme => 'twitter-bootstrap-3',
		    :pagination_class => "pagination pagination-sm" %>
		</div>
		
		<div class="col-sm-6 text-justify" >
			<%= render 'tag/cloud', tags: @tags %>
		</div>
	</div>
</div>

<div class="container-fluid">
	<% @notes.each do |note| %>
	    <%= render 'note_summary', note: note %>
	<% end %>
</div>

<%= paginate @notes, :theme => 'twitter-bootstrap-3',
:pagination_class => "pagination pagination-sm" %>


<br>

<%= link_to 'New Note', new_note_path %>

app/views/notes/new.html.erb
<% title "New Note" %>

<h1><%= yield :title %></h1>

<%= render 'form', note: @note %>

<br>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<% title @note.title %>

<div class="row" id="workspace_header">
	<div class="col-sm-8" id="workspace_title">
		<h1><%= yield :title %></h1>
	  <p id="workspace_header_summary"><%= @note.summary %></p>
	</div>
	<div class="col-sm-4" id="workspace_header_infos">
	  <p>
	    Created on <%= @note.created_at.localtime.strftime("%A, %b %d, %Y at %H:%M") %><br>
	    Last updated on <%= @note.updated_at.localtime.strftime("%A, %b %d, %Y at %H:%M") %><br>
	    <a href="#">See the history</a>
	  </p>
	  <p>
	    <%= sanitize @note.tag_list.map { |t| link_to t, tag_path(t) }.join(', '), tags: %w(a), attributes: %w(href ) %>
	  </p>
	</div>
</div>



<div class="row" id="workspace_menu">
	<div class="col-sm-8" id="workspace_menu_main">
	  <%= render "documents/n_documents", :note => @note %>
	  <%= render "to_dos/n_to_dos", :note => @note %>
	  Add new: 
	  <%= link_to 'Document or file', new_document_path(note_id: @note.id) %>
	  <%= link_to 'Task', new_to_do_path(note_id: @note.id) %>
	</div>
	<div class="col-sm-4 menu_edit" id="workspace_menu_context">
	  This note: 
	  <%= link_to 'Edit', edit_note_path(@note) %>
	  <a href="#">Copy</a> 
	  <%= link_to 'Delete', @note, method: :delete, data: { confirm: 'Are you sure?' } %>               
	</div>
</div>

<div class="row" id="workspace_content">
  <div class="col-sm-8 note_text">
    <%= sanitize @note.text,
    		tags: %w(h1 h2 h3 h4 h5 p br ul ol li strong em u a hr blockquote img table th tr td),
    		attributes: %w(href src alt) %>
  </div>
  <div class="col-sm-4" id="workspace_tools">
  	<% if @note.documents.length != 0 %>



	  	<h4>Documents and files</h4>
			<ul class="media-list">
		  	<% @note.documents.each do |document| %>
				  <li class="media">
				    <div class="media-left">
				      <%= if document.file?
				      			link_to document.download_url do %>
				      <%= image_tag document.file_url(:small_thumb),
				      				class: "media-object thumb" %>
				      	<% end
				      	end %>
				    </div>
				    <div class="media-body">
				      <h4 class="media-heading"><%= link_to document.title, document -%></h4>
				      <p class="document-list">
				      	<%= truncate document.summary, length: 120, separator: ' ' -%>
    					</p>
    					<p class="document-list">
		    				<%= link_to 'Download', document.download_url %>
    						(<%= number_to_human_size document.file.size -%>,
     						 <%= document.file.file.extension.downcase-%>)
    					</p>
				    </div>
				  </li>
		    <% end %>
			</ul>
	  <% end %>
	  <%= link_to 'Upload a new document or a new file', new_document_path(note_id: @note.id) %>

	  <br>
	  <% if @note.has_to_dos? %>
	    <% label =  todo_label @note.to_dos %>
	    <h4 style="margin-top: 30px;">To-Do's
	    <% if label[:number] != 0 %>
	    	<span class="badge progress-bar-<%= label[:label]-%>">
	      <%= label[:number] -%></span>
	    <% end %>
	    </h4>
	    <%= render 'to_dos/todo_list', tasks: @note.to_dos.order(:achieved, deadline: :asc) %>
	  <% end %>
	  <%= link_to 'Add a new task', new_to_do_path(note_id: @note.id) %>
	</div>
</div>