config/routes.rb
Rails.application.routes.draw do
  resources :documents
  resources :to_dos
  get 'tags/', to: 'dashboard#index'
  get 'tags/:tag', to: 'tag#index', as: :tag
  resources :notes
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'dashboard#index'
end

app/models/document.rb
require 'elasticsearch/model'

class Document < ApplicationRecord
  belongs_to :user
  belongs_to :note, optional: true

  acts_as_taggable
  mount_uploader :file, FileUploader

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  def download_url
  	if self.use_main_link
  		return self.main_link
  	else
  		return self.file_url
  	end
  end

  def self.search(query)
    __elasticsearch__.search(
      {
        query: {
          multi_match: {
            query: query,
            fields: ['title^10', 'author^5', 'summary']
          }
        }
      }
    )
  end
  
end

Document.import force: true

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :update_files, :destroy]

  # GET /documents
  # GET /documents.json
  def index
    if params[:q].nil? or params[:q]==""
      @documents = current_user.documents
    else
      @documents = current_user.documents.search(params[:q]).records
    end
    @tags = @documents.tag_counts
    if(params[:note_id])
      @documents = @documents.where(note_id: params[:note_id])
    end
    @documents = @documents.order(updated_at: :desc).page(params[:page]).per(5)
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
    if params[:note_id]
      @note = Note.find(params[:note_id])
      @document.note = @note
      @document.tag_list = @note.tag_list
    end
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)
    @document.user = current_user

    if params[:note_id]
      @note = Note.find(params[:note_id])
      @document.note = @note
    end

    respond_to do |format|
      if @document.save
        @document.__elasticsearch__.index_document
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        if params[:update_files]
          begin
            @document.file.cache_stored_file!
            @document.file.retrieve_from_cache!(@document.file.cache_name)
            @document.file.recreate_versions!
            @document.save!
          rescue => e
            format.html { render :edit }
            format.json { render json: @document.errors, status: :unprocessable_entity }
          end
        end
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_files
    respond_to do |format|
      begin
        @document.file.cache_stored_file!
        @document.file.retrieve_from_cache!(@document.file.cache_name)
        @document.file.recreate_versions!
        @document.save!
        format.html { redirect_to @document, notice: 'The files were successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      rescue => e
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = current_user.documents.find(params[:id]) # Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:title, :author, :summary, :user_id, :note_id, :file, :remote_file_url, :tag_list, :main_link, :use_main_link)
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_document_summary.html.erb
<div class="row" style="margin-bottom: 20px;margin-top: 20px;">
    <div class="col-sm-8">
        
        <div class="container-fluid">
            <div class="row">
                <%= link_to document do %>
                    <div class="col-sm-12 note">
                        <h2><%= document.title %></h2>
                        <p class="note_summary"><%= document.summary %></p>
                    </div>
                <% end %>
             </div>
            <div class="row">
                <div class="col-sm-4">
                    <%= link_to 'Edit', edit_document_path(document),
                        class: "btn btn-warning btn-sm" %>
                    <%= link_to 'Delete', document, method: :delete,
                        class: "btn btn-danger btn-sm",
                        data: { confirm: 'Are you sure?' } %>
                </div>
                <div class="col-sm-4">
                    <p>Tags:
                        <%= sanitize document.tag_list.map { |t| link_to t, tag_path(t) }.join(', '), tags: %w(a), attributes: %w(href ) %>
                    </p>
                </div>
                <div class="col-sm-4 text-right">
                    <p class="note_infos text-right">
                        Created on <%= document.created_at.localtime.strftime("%a, %b %d, %Y at %H:%M") %><br>
                        Last updated on <%= document.updated_at.localtime.strftime("%a, %b %d, %Y at %H:%M") %><br>
                    </p>
                </div> 
            </div>
        </div>

    </div>
    <div class="col-sm-3" style="padding-top: 5px;">
        <div class="media-left">
          <%= if document.file?
                    link_to document.download_url do %>
          <%= image_tag document.file_url(:small_thumb),
                        class: "media-object thumb" %>
            <% end
            end %>
        </div>
        <div class="media-body">
          <h4 class="media-heading"><%= link_to document.title, document -%></h4>
            <p class="document-list">
                <%= link_to 'Download', document.download_url %>
                (<%= number_to_human_size document.file.size -%>,
                 <%= document.file.file.extension.downcase-%>)
            </p>
        </div>
    </div>
</div>

app/views/documents/_form.html.erb
<%= form_for document, :html => {:multipart => true}  do |f| %>
  <% if document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @document.note %>
    <%= hidden_field_tag :note_id, @document.note_id %>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :author %>
    <%= f.text_field :author, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :summary %>
    <%= f.text_area :summary, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :tag_list, "Tags (separated by commas)" %><br />
    <%= f.text_field :tag_list, value: document.tag_list.map {|t| t}.join(', '), class: "form-control" %>
  </div>

  <div class="container-fluid">
    <div class="row">
    <% if @document.file? %>
      <div class="col-sm-1 text-right" style="margin-left: -15px;">
        <%= link_to document.download_url do 
              image_tag @document.file_url(:small_thumb), class: "media-object thumb"
            end %>
      </div>
      <div class="col-sm-5">
        <div class="form-group">
          <%= f.label :file, "Upload a new file..." %>
          <%= f.file_field :file %><br />
        </div>
      </div>
    <% else %>
      <div class="col-sm-6" style="margin-left: -15px;">
        <div class="form-group">
          <%= f.label :file, "Upload a local file..." %>
          <%= f.file_field :file %><br />
        </div>
      </div>
    <% end %>
      <div class="col-sm-6" style="padding-right: 0px;">
        <div class="form-group">
          <%= f.label :remote_file_url, "... or give a file URL" %>
          <%= f.text_field :remote_file_url, class: "form-control" %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12" style="margin-left: -15px; padding-right: 0px;">
        <div class="form-group">
          <%= f.label :main_link, "External link" %>
          (&nbsp;<%= f.check_box :use_main_link %> <%= f.label "Use this link as download link in myNotes.", style: "font-weight: normal" %>&nbsp;)
          <%= f.text_field :main_link, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>


  <% if @document.id %>
    <div class="form-group">
      <%= check_box_tag :update_files %> Recreate the thumbnail images
    </div>
  <% end %>


  <div class="actions">
    <%= f.submit "Save & Quit", class: "btn btn-primary btn-sm" %>
  </div>

  



  

  

<% end %>

app/views/documents/_n_documents.html.erb
<%=
	if note.has_documents?
		link_to pluralize(note.documents.length, "document"),
			documents_path(note_id: note.id)
	end
%>

app/views/documents/edit.html.erb
<% title @document.title %>	

<h1></h1>

<%= render 'form', document: @document %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/index.html.erb
<% title "Documents" %>

<div class="container-fluid">
	<div class="row">
		<div class="col-sm-6">
			<h1><%= yield :title %></h1>
		</div>
		<div class="col-sm-6 text-right" style="padding-top: 18px">

			<%= form_tag('/documents', method: :get, class: "form-inline") do  %>
				<div class="form-group">
			    <%= text_field_tag :q, params[:q], class: "form-control"  %>
				</div>
				<%= submit_tag "Search", class: "btn btn-primary btn-sm" %>
			<% end %>

			
		</div>
	</div>
	<div class="row">
		<div class="col-sm-6">
		<%= paginate @documents, :theme => 'twitter-bootstrap-3',
		    :pagination_class => "pagination pagination-sm" %>
		</div>
		
		<div class="col-sm-6 text-justify" >
			<%= render 'tag/cloud', tags: @tags %>
		</div>
	</div>
</div>


<div class="container-fluid">
  <% @documents.each do |document| %>
      <%= render 'document_summary', document: document %>
  <% end %>
</div>

<%= paginate @documents, :theme => 'twitter-bootstrap-3',
:pagination_class => "pagination pagination-sm" %>


<br>

<%= link_to 'New Document', new_document_path %>

app/views/documents/new.html.erb
<% title "New Document" %>

<h1><%= yield :title %></h1>

<%= render 'form', document: @document %>

<br>

<%= link_to 'Back', documents_path %>

app/views/documents/show.html.erb
<% title @document.title %>

<div class="row" id="workspace_header">
  <div class="col-sm-8" id="workspace_title">
    <h1><%= yield :title %></h1>
    <p id="workspace_header_summary"><%= @document.summary %></p>
  </div>
  <div class="col-sm-4" id="workspace_header_infos">
    <p>
      Created on <%= @document.created_at.localtime.strftime("%A, %b %d, %Y at %H:%M") %><br>
      Last updated on <%= @document.updated_at.localtime.strftime("%A, %b %d, %Y at %H:%M") %>
    </p>
    <p>
      <%= sanitize @document.tag_list.map { |t| link_to t, tag_path(t) }.join(', '), tags: %w(a), attributes: %w(href ) %>
    </p>
  </div>
</div>



<div class="row" id="workspace_menu">
  <div class="col-sm-6" id="workspace_menu_main">
    <% if @document.note %>
      Linked to: <%= link_to @document.note.title, @document.note %>
    <% end %>
  </div>
  <div class="col-sm-6 menu_edit" id="workspace_menu_context">
    This document:
    <%= link_to 'Download', @document.download_url %>
    (<%= number_to_human_size @document.file.size -%>,
     <%= @document.file.file.extension.downcase-%>)
    <%= link_to 'Edit', edit_document_path(@document) %>
    <%= link_to 'Delete', @document, method: :delete, data: { confirm: 'Are you sure?' } %>               
  </div>
</div>


<div class="container-fluid">
  <div class="row" id="workspace_content">
    <div class="col-sm-6 cover-image text-center">
      <%= link_to @document.download_url do %>
        <%= image_tag @document.file_url(:cover), class: "img-responsive cover" if @document.file? %>
      <% end %>
    </div>
    <div class="col-sm-6 note-text" id="workspace_tools">
    <% if @document.note %>
        Associated note:
        <%= link_to @document.note do %>
          <h2><%= @document.note.title %></h2>
        <% end %>
        <p><%= @document.note.summary %></p>
        <hr>
        <%= sanitize @document.note.text,
          tags: %w(h2 h3 h4 h5 p br ul ol li strong em u a hr blockquote img),
          attributes: %w(href src alt), class: "note-text" %>

    <% end %>
    </div>
  </div>
</div>