config/routes.rb
Rails.application.routes.draw do
  resources :documents
  resources :to_dos
  get 'tags/', to: 'dashboard#index'
  get 'tags/:tag', to: 'tag#index', as: :tag
  resources :notes
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'dashboard#index'
end

app/models/to_do.rb
require 'elasticsearch/model'

class ToDo < ApplicationRecord
	belongs_to :user
	belongs_to :note, optional: true
	acts_as_taggable


  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  
  def not_achieved?
    return not(self.achieved)
  end


  def label
    if self.achieved
      return "default"
    end

    if self.deadline < Time.now	
      return "danger" # Too late
    else
      if self.deadline.today?
        return "warning" # For today
      else
        return "success" # For later on
      end
    end
  end

  def tag_to_text
    tag_list.map { |t| t}.join(' ')
  end


  def independent?
    if self.note_id.nil?
      return true
    else
      return false
    end
  end

  def self.search(query)
    __elasticsearch__.search(
      {
        query: {
          multi_match: {
            query: query,
            fields: ['title^10', 'text', 'tag_to_text']
          }
        }
      }
    )
  end

end

ToDo.import force: true

app/controllers/to_dos_controller.rb
class ToDosController < ApplicationController
  before_action :set_to_do, only: [:show, :edit, :update, :destroy]

  # GET /to_dos
  # GET /to_dos.json
  def index
    if params[:q].nil? or params[:q]==""
      @to_dos = current_user.to_dos
    else
      @to_dos = current_user.to_dos.search(params[:q]).records
    end
    @tags = @to_dos.tag_counts.order(taggings_count: :desc).first(40).sort_by {|t| t.name}

    if params[:tag]
      @tag = params[:tag]
      @to_dos = @to_dos.tagged_with(params[:tag])
    elsif params[:note_id]
      @to_dos = @to_dos.where(note_id: params[:note_id].to_i)
    end
    ## TODO: Manage display_all param: all todos: only open, todos of a note: all
    if not(params[:display_all])
      @to_dos = @to_dos.where(displayed: "true").order(deadline: :asc)
    end
    @to_dos = @to_dos.order(deadline: :asc).page(params[:page]).per(5)
  end

  # GET /to_dos/1
  # GET /to_dos/1.json
  def show
  end

  # GET /to_dos/new
  def new
    @to_do = ToDo.new
    if params[:note_id]
      @note = Note.find(params[:note_id])
      @to_do.note = @note
      @to_do.tag_list = @note.tag_list
    end
    @to_do.displayed = true
  end

  # GET /to_dos/1/edit
  def edit
  end

  # POST /to_dos
  # POST /to_dos.json
  def create
    @to_do = ToDo.new(to_do_params)
    @to_do.user = current_user
    if params[:note_id]
      @note = Note.find(params[:note_id])
      @to_do.note = @note
    end

    respond_to do |format|
      if @to_do.save
        @to_do.__elasticsearch__.index_document
        format.html { redirect_to @to_do, notice: 'To do was successfully created.' }
        format.js
        format.json { render "to_do", status: :created, to_do: @to_do }
      else
        format.html { render :new }
        format.json { render json: @to_do.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /to_dos/1
  # PATCH/PUT /to_dos/1.json
  def update
    respond_to do |format|
      if @to_do.update(to_do_params)
        format.html { redirect_to :to_dos, notice: 'To do was successfully updated.' }
        format.json { render :show, status: :ok, location: @to_do }
      else
        format.html { render :edit }
        format.json { render json: @to_do.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /to_dos/1
  # DELETE /to_dos/1.json
  def destroy
    @to_do.destroy
    respond_to do |format|
      format.html { redirect_to to_dos_url, notice: 'To do was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_to_do
      @to_do = current_user.to_dos.find(params[:id]) # ToDo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def to_do_params
      params.require(:to_do).permit(:title, :text, :status, :deadline, :displayed, :achieved, :user, :note, :tag_list)
    end
end

app/helpers/to_dos_helper.rb
module ToDosHelper

  # Indicates a summary of a whole todo's list:
  # - If there are late notes: the label is their number
  # - If there are no late notes, the label is the number of
  #   the notes that are due for today
  def todo_label (list)
		open = 0
		today = 0
		late = 0
		# Scans the list and counts late and today's tasks
		list.each do |t|
			if t.not_achieved?
				if t.deadline < Time.now
					late = late +1
				elsif t.deadline.today?
					today = today +1
				else
					open = open + 1
				end
			end
		end
		# Defines the 'label' and 'number' output values
		if late != 0
			label = "danger"
			number = late
		elsif today != 0
			label = "warning"
			number = today
		else
			label = "success"
			number = open
		end

		return {:label => label, :number => number}

  end

end

app/views/to_dos/_form.html.erb
<%= form_for(to_do) do |f| %>
  <% if to_do.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(to_do.errors.count, "error") %> prohibited this to_do from being saved:</h2>

      <ul>
      <% to_do.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @to_do.note %>
    <%= hidden_field_tag :note_id, @to_do.note_id %>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :text %>
    <%= f.text_area :text, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :status %>
    <%= f.text_field :status, class: "form-control" %>
  </div>


  <div class="form-group">
    <%= f.label :tag_list, "Tags (separated by commas)" %><br />
    <%= f.text_field :tag_list, value: to_do.tag_list.map {|t| t}.join(', '), class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :deadline %>
    <%= f.text_field :deadline %>
  </div>

  <div class="form-group">
    <%= f.check_box :achieved %>
    <%= f.label :achieved %>
  </div>

  <div class="form-group">
    <%= f.check_box :displayed %>
    <%= f.label :displayed %>
  </div>




  <div class="actions">
    <%= f.submit "Save & Quit", class: "btn btn-primary btn-sm" %>
  </div>
<% end %>

app/views/to_dos/_n_to_dos.html.erb
<%=
	if note.has_to_dos?
		link_to pluralize(note.to_dos.length, "To-Do", plural: "To-Do's"),
			to_dos_path(note_id: note.id, display_all: :true)
	end
%>

app/views/to_dos/_short_form.html.erb
<%= form_for @to_do, remote: true do |f| %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :text %>
    <%= f.text_area :text, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :deadline %>
    <%= f.datetime_select :deadline, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit "Create", class: "btn btn-primary btn-sm" %>
  </div>
<% end %>

app/views/to_dos/_to_do.html.erb
<div class="panel panel-<%= to_do.label -%>">
	<div class="panel-heading">
  	<div class="row">
  		<div class="col-sm-9">
	  		<h4 class="text-<%= to_do.label -%>" style="margin:0px">
	  			<input type="checkbox" style="display: inline;">
	  			<%= to_do.title %>
	  		</h4>
  		</div>
  		<div class="col-sm-3 text-right">
  			<small class="label label-<%= to_do.label  -%>">
				<%= to_do.deadline.localtime.strftime("%a, %b %d, %Y at %H:%M") %></small>
  		</div>
  	</div>
  </div>
	<div class="panel-body">
		<div class="row">
  		<div class="col-sm-7">
  			<p class="text-<%= to_do.label -%>">
  				<%= h to_do.text %><br>
  			</p>
  		</div>
  		<div class="col-sm-5 text-right">
	  		<p class="note_infos text-right">
					Created on
					<%= to_do.created_at.localtime.strftime("%a, %b %d, %Y at %H:%M") %><br>
					Last updated on
					<%= to_do.updated_at.localtime.strftime("%a, %b %d, %Y at %H:%M") %><br>
				</p>
					<%= link_to 'Edit', edit_to_do_path(to_do),
						class: "btn btn-warning btn-xs" %>
					<%= link_to 'Delete', to_do, method: :delete,
						class: "btn btn-danger btn-xs",
						data: { confirm: 'Are you sure?' } %>
			</div>
	  </div>
	</div>
</div>

app/views/to_dos/_to_do_summary.html.erb
<div class="row" style="margin-bottom: 20px;margin-top: 20px;">
	<div class="col-sm-8">

		<div class="container-fluid">     
		
			<div class="row">
				<div class="col-sm-12 todo">
					<h2 class="todo text-<%= to_do.label -%>"><%= to_do.title %></h2>
					<p><%= to_do.text %></p>
					<p><small class="label label-<%= to_do.label  -%>"><%= to_do.deadline.localtime.strftime("%a, %b %d, %Y at %H:%M") %></small>
					</p>
					
				</div>
			</div>

			<div class="row">
				<div class="col-sm-4">
					<%= link_to 'Edit', edit_to_do_path(to_do),
					class: "btn btn-warning btn-sm" %>
					<%= link_to 'Delete', to_do, method: :delete,
					class: "btn btn-danger btn-sm",
					data: { confirm: 'Are you sure?' } %>
				</div>
				<div class="col-sm-4">
					<p>Tags:
					<%= sanitize to_do.tag_list.map { |t| link_to t, tag_path(t) }.join(', '), tags: %w(a), attributes: %w(href ) %>
					</p>
				</div>
				<div class="col-sm-4 text-right">
					<p class="note_infos text-right">
					Created on <%= to_do.created_at.localtime.strftime("%a, %b %d, %Y at %H:%M") %><br>
					Last updated on <%= to_do.updated_at.localtime.strftime("%a, %b %d, %Y at %H:%M") %><br>
					</p>
				</div> 
			</div>
		
		</div>

	</div>
</div>

app/views/to_dos/_todo_list.html.erb
<ul class="todos_list">
	<% tasks.each do |task| %>
	    <li class="text-<%= task.label  -%>">
	        <%= task.title %>
	        <span class="label label-<%= task.label  -%>"><%= task.deadline.localtime.strftime("%a, %b %d, %Y at %H:%M") %></span>
	    </li>
	<% end %>
</ul>

app/views/to_dos/create.js.erb
$('#new_link').show();
$('#tasks_list').append('<%= j render("to_do"), to_do: @to_do %>');

app/views/to_dos/edit.html.erb
<% title @to_do.title %>

<h1><%= yield :title %></h1>

<%= render 'form', to_do: @to_do %>

<%= link_to 'Show', @to_do %> |
<%= link_to 'Back', to_dos_path %>

app/views/to_dos/index.html.erb
<% title "To-Do's" %>

<div class="container-fluid">

	<div class="row">
		<div class="col-sm-6">
			<h1><%= yield :title %></h1>
		</div>
		<div class="col-sm-6 text-right" style="padding-top: 18px">

			<%= form_tag('/to_dos', method: :get, class: "form-inline") do  %>
				<div class="form-group">
			    <%= text_field_tag :q, params[:q], class: "form-control"  %>
				</div>
				<%= submit_tag "Search", class: "btn btn-primary btn-sm" %>
			<% end %>
		</div>
	</div>

	<div class="row">
		<div class="col-sm-8">
		<%= paginate @to_dos, :theme => 'twitter-bootstrap-3',
		    :pagination_class => "pagination pagination-sm" %>
		</div>
	</div> 
	<div class="row">
		<div class="col-sm-8">
		<div>
			<%= link_to "Add a new task", new_to_do_path, id: "new_link", remote: true %><br><br>
		</div>
	</div>

	<div class="row">
		<div class="col-sm-12" id="tasks_list">
			<% @to_dos.each do |to_do| %>
				<%= render to_do %>	
			<% end %>
		</div>
	</div>

	<div class="row">
		<div class="col-sm-12">
		<%= paginate @to_dos, :theme => 'twitter-bootstrap-3',
		    :pagination_class => "pagination pagination-sm" %>
		</div>
	</div>

</div>

app/views/to_dos/new.html.erb
<% title "New Task" %>

<h1><%= yield :title %></h1>

<%= render 'form', to_do: @to_do %>

<br>

<%= link_to 'Back', to_dos_path %>

app/views/to_dos/new.js.erb
$('#new_link').hide().after('<%= j render("short_form") %>')

app/views/to_dos/show.html.erb
<% title @to_do.title %>

<h1><%= yield :title %></h1>
<p>
  <strong>Title:</strong>
  <%= @to_do.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @to_do.text %>
</p>

<p>
  <strong>Status:</strong>
  <%= @to_do.status %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @to_do.deadline %>
</p>

<p>
  <strong>Displayed:</strong>
  <%= @to_do.displayed %>
</p>

<p>
  <strong>Achieved:</strong>
  <%= @to_do.achieved %>
</p>

<p>
  <strong>User:</strong>
  <%= @to_do.user %>
</p>

<p>
  <strong>Note:</strong>
  <%= @to_do.note %>
</p>

<%= link_to 'Edit', edit_to_do_path(@to_do) %> |
<%= link_to 'Back', to_dos_path %>